default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: test_scraper_.*\.json
      - id: check-ast
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--config, .config/ruff.toml, --fix]
      # Run the formatter.
      - id: ruff-format
        args: [--config, .config/ruff.toml]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.2.37
    hooks:
      # Run the pip compile
      - id: pip-compile
        name: pip-compile requirements.txt
        files: requirements/requirements.in
        args: [ requirements/requirements.in, --resolver=backtracking, --upgrade, -q,
                -o, requirements/requirements.txt ]
      - id: pip-compile
        name: pip-compile requirements-test.txt
        files: requirements/requirements-test.in
        args: [ requirements/requirements-test.in, --resolver=backtracking, --upgrade, -q,
                -o, requirements/requirements-test.txt ]
      - id: pip-compile
        name: pip-compile requirements-analysis.txt
        files: requirements/requirements-analysis.in
        args: [ requirements/requirements-analysis.in, --resolver=backtracking, --upgrade, -q,
                  -o, requirements/requirements-analysis.txt ]
